{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "firecracker-runner.serviceAccountName" . }}
  namespace: {{ include "firecracker-runner.namespace" . }}
  labels:
{{ include "firecracker-runner.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}


