{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "firecracker-runner.fullname" . }}
  namespace: {{ include "firecracker-runner.namespace" . }}
  labels:
{{ include "firecracker-runner.labels" . | indent 4 }}
{{- with .Values.monitoring.serviceMonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
{{ include "firecracker-runner.selectorLabels" . | indent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}


