apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecracker-runner.fullname" . }}
  namespace: {{ include "firecracker-runner.namespace" . }}
  labels:
{{ include "firecracker-runner.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "firecracker-runner.selectorLabels" . | indent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http


